import type { Metadata } from "next";
import { Inter  } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Nebs-IT Dashboard",
  description: "Generated by Nebs-IT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={`${inter.variable} text-[#232948]`}
      >
        {children}
      </body>
    </html>
  );
}
